on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Setup environment
      uses: actions/setup-dotnet@v3.3.1
      with:
        dotnet-version: 6.0
  
    - name: .NET Clean
      run: dotnet clean
      
    - name: Restore dependencies
      run: dotnet restore
  
    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release

    env:
      user_name: 'github-actions[bot]'
      user_email: 'github-actions[bot]@users.noreply.github.com'
  
        
      
